settings["webhook"] := {enum: 1, type: "str", section: "Status", regex: "i)^(https:\/\/(canary\.|ptb\.)?(discord|discordapp)\.com\/api\/webhooks\/([\d]+)\/([a-z0-9_-]+)|<blank>)$"}
;settings["bottoken"] := {enum: 2, type: "str", section: "Status", regex: "i)^[\w-.]{50,83}$"} dangerous
;settings["MainChannelID"] := {enum: 3, type: "str", section: "Status", regex: "i)^\d{17,20}$"} dangerous
settings["ReportChannelID"] := {enum: 4, type: "str", section: "Status", regex: "i)^\d{17,20}$"}
settings["discordUID"] := {enum: 5, type: "str", section: "Status", regex: "i)^&?\d{17,20}$"}
settings["commandPrefix"] := {enum: 6, type: "str", section: "Status", regex: "i)^\S{1,3}$"}
settings["MoveMethod"] := {enum: 7, type: "str", section: "Settings", regex: "i)^(cannon|walk)$"}
settings["SprinklerType"] := {enum: 8, type: "str", section: "Settings", regex: "i)^(none|basic|silver|golden|diamond|supreme)$"}
settings["ConvertBalloon"] := {enum: 9, type: "str", section: "Settings", regex: "i)^(always|never|every|gather)$"}
settings["PrivServer"] := {enum: 10, type: "str", section: "Settings", regex: "i)^(((http(s)?):\/\/)?((www|web)\.)?roblox\.com\/games\/1537690962\/?([^\/]*)\?privateServerLinkCode=.{32}(\&[^\/]*)*|<blank>)$"}
settings["FieldName1"] := {enum: 11, type: "str", section: "Gather", regex: "i)^(Bamboo|Blue Flower|Cactus|Clover|Coconut|Dandelion|Mountain Top|Mushroom|Pepper|Pine Tree|Pineapple|Pumpkin|Rose|Spider|Strawberry|Stump|Sunflower)$"}
settings["FieldName2"] := {enum: 12, type: "str", section: "Gather", regex: "i)^(None|Bamboo|Blue Flower|Cactus|Clover|Coconut|Dandelion|Mountain Top|Mushroom|Pepper|Pine Tree|Pineapple|Pumpkin|Rose|Spider|Strawberry|Stump|Sunflower)$"}
settings["FieldName3"] := {enum: 13, type: "str", section: "Gather", regex: "i)^(None|Bamboo|Blue Flower|Cactus|Clover|Coconut|Dandelion|Mountain Top|Mushroom|Pepper|Pine Tree|Pineapple|Pumpkin|Rose|Spider|Strawberry|Stump|Sunflower)$"}
settings["FieldPattern1"] := {enum: 14, type: "str", section: "Gather", regex: "i)^(" patternlist ")$"}
settings["FieldPattern2"] := {enum: 15, type: "str", section: "Gather", regex: "i)^(" patternlist ")$"}
settings["FieldPattern3"] := {enum: 16, type: "str", section: "Gather", regex: "i)^(" patternlist ")$"}
settings["FieldPatternSize1"] := {enum: 17, type: "str", section: "Gather", regex: "i)^(XS|S|M|L|XL)$"}
settings["FieldPatternSize2"] := {enum: 18, type: "str", section: "Gather", regex: "i)^(XS|S|M|L|XL)$"}
settings["FieldPatternSize3"] := {enum: 19, type: "str", section: "Gather", regex: "i)^(XS|S|M|L|XL)$"}
settings["FieldReturnType1"] := {enum: 20, type: "str", section: "Gather", regex: "i)^(Walk|Reset)$"}
settings["FieldReturnType2"] := {enum: 21, type: "str", section: "Gather", regex: "i)^(Walk|Reset)$"}
settings["FieldReturnType3"] := {enum: 22, type: "str", section: "Gather", regex: "i)^(Walk|Reset)$"}
settings["FieldSprinklerLoc1"] := {enum: 23, type: "str", section: "Gather", regex: "i)^(Center|Upper Left|Upper|Upper Right|Right|Lower Right|Lower|Lower Left|Left)$"}
settings["FieldSprinklerLoc2"] := {enum: 24, type: "str", section: "Gather", regex: "i)^(Center|Upper Left|Upper|Upper Right|Right|Lower Right|Lower|Lower Left|Left)$"}
settings["FieldSprinklerLoc3"] := {enum: 25, type: "str", section: "Gather", regex: "i)^(Center|Upper Left|Upper|Upper Right|Right|Lower Right|Lower|Lower Left|Left)$"}
settings["FieldRotateDirection1"] := {enum: 26, type: "str", section: "Gather", regex: "i)^(None|Left|Right)$"}
settings["FieldRotateDirection2"] := {enum: 27, type: "str", section: "Gather", regex: "i)^(None|Left|Right)$"}
settings["FieldRotateDirection3"] := {enum: 28, type: "str", section: "Gather", regex: "i)^(None|Left|Right)$"}
settings["MondoAction"] := {enum: 29, type: "str", section: "Collect", regex: "i)^(Buff|Kill|Tag|Guid)$"}
settings["AntPassAction"] := {enum: 30, type: "str", section: "Collect", regex: "i)^(Pass|Challenge)$"}
settings["FieldBooster1"] := {enum: 31, type: "str", section: "Boost", regex: "i)^(None|Blue|Red|Mountain)$"}
settings["FieldBooster2"] := {enum: 32, type: "str", section: "Boost", regex: "i)^(None|Blue|Red|Mountain)$"}
settings["FieldBooster3"] := {enum: 33, type: "str", section: "Boost", regex: "i)^(None|Blue|Red|Mountain)$"}
settings["HotbarWhile2"] := {enum: 34, type: "str", section: "Boost", regex: "i)^(Never|Always|At Hive|Gathering|Attacking|Microconverter|Whirligig|Enzymes|GatherStart|Snowflake|Glitter)$"}
settings["HotbarWhile3"] := {enum: 35, type: "str", section: "Boost", regex: "i)^(Never|Always|At Hive|Gathering|Attacking|Microconverter|Whirligig|Enzymes|GatherStart|Snowflake|Glitter)$"}
settings["HotbarWhile4"] := {enum: 36, type: "str", section: "Boost", regex: "i)^(Never|Always|At Hive|Gathering|Attacking|Microconverter|Whirligig|Enzymes|GatherStart|Snowflake|Glitter)$"}
settings["HotbarWhile5"] := {enum: 37, type: "str", section: "Boost", regex: "i)^(Never|Always|At Hive|Gathering|Attacking|Microconverter|Whirligig|Enzymes|GatherStart|Snowflake|Glitter)$"}
settings["HotbarWhile6"] := {enum: 38, type: "str", section: "Boost", regex: "i)^(Never|Always|At Hive|Gathering|Attacking|Microconverter|Whirligig|Enzymes|GatherStart|Snowflake|Glitter)$"}
settings["HotbarWhile7"] := {enum: 39, type: "str", section: "Boost", regex: "i)^(Never|Always|At Hive|Gathering|Attacking|Microconverter|Whirligig|Enzymes|GatherStart|Snowflake|Glitter)$"}
settings["QuestGatherReturnBy"] := {enum: 40, type: "str", section: "Quests", regex: "i)^(Walk|Reset)$"}
settings["MoveSpeedNum"] := {enum: 41, type: "str", section: "Settings", regex: "i)^[1-9]\d(\.\d{1,3})?$"}
settings["ReconnectInterval"] := {enum: 42, type: "str", section: "Settings", regex: "i)^(1|2|3|4|6|8|12|24|<blank>)$"}
settings["ReconnectHour"] := {enum: 43, type: "str", section: "Settings", regex: "i)^(([0-1]?[0-9]|2[0-3])|<blank>)$"}
settings["ReconnectMin"] := {enum: 44, type: "str", section: "Settings", regex: "i)^(([0-5]?[0-9])?|<blank>)$"}
settings["FallbackServer1"] := {enum: 45, type: "str", section: "Settings", regex: "i)^(((http(s)?):\/\/)?((www|web)\.)?roblox\.com\/games\/1537690962\/?([^\/]*)\?privateServerLinkCode=.{32}(\&[^\/]*)*|<blank>)$"}
settings["FallbackServer2"] := {enum: 46, type: "str", section: "Settings", regex: "i)^(((http(s)?):\/\/)?((www|web)\.)?roblox\.com\/games\/1537690962\/?([^\/]*)\?privateServerLinkCode=.{32}(\&[^\/]*)*|<blank>)$"}
settings["FallbackServer3"] := {enum: 47, type: "str", section: "Settings", regex: "i)^(((http(s)?):\/\/)?((www|web)\.)?roblox\.com\/games\/1537690962\/?([^\/]*)\?privateServerLinkCode=.{32}(\&[^\/]*)*|<blank>)$"}
settings["NightAnnouncementName"] := {enum: 48, type: "str", section: "Status", regex: "i)^[^\\]$"}
settings["NightAnnouncementPingID"] := {enum: 49, type: "str", section: "Status", regex: "i)^((&?[0-9]*)|<blank>)$"}
settings["NightAnnouncementWebhook"] := {enum: 50, type: "str", section: "Status", regex: "i)^(https:\/\/(canary\.|ptb\.)?(discord|discordapp)\.com\/api\/webhooks\/([\d]+)\/([a-z0-9_-]+)|<blank>)$"}
settings["SnailTime"] := {enum: 51, type: "str", section: "Collect", regex: "i)^(5|10|15|Kill)$"}
settings["ChickTime"] := {enum: 52, type: "str", section: "Collect", regex: "i)^(5|10|15|Kill)$"}
settings["InputSnailHealth"] := {enum: 53, type: "str", section: "Collect", regex: "i)^(?:100(?:\.00?)?|\d?\d(?:\.\d\d?)?)$"}
settings["InputChickHealth"] := {enum: 54, type: "str", section: "Collect", regex: "i)^(?:100(?:\.00?)?|\d?\d(?:\.\d\d?)?)$"}
settings["ShrineItem1"] := {enum: 55, type: "str", section: "Shrine", regex: "i)^(strawberries|sunflowers|pineapples|Blueberries|blueextract|redextract|glue|oil|enzymes|gumdrops|tropicaldrink|mooncharms|glitter|starjelly|purplepotion|antpass|cloudvial|softwax|hardwax|swirledwax|causticwax|fielddice|smoothdice|loadeddice|Turpentine)$"}
settings["ShrineItem2"] := {enum: 56, type: "str", section: "Shrine", regex: "i)^(strawberries|sunflowers|pineapples|Blueberries|blueextract|redextract|glue|oil|enzymes|gumdrops|tropicaldrink|mooncharms|glitter|starjelly|purplepotion|antpass|cloudvial|softwax|hardwax|swirledwax|causticwax|fielddice|smoothdice|loadeddice|Turpentine)$"}
settings["ShrineIndex1"] := {enum: 57, type: "str", section: "Shrine", regex: "i)^(Infinite|\d{1,3})$"}
settings["ShrineIndex2"] := {enum: 58, type: "str", section: "Shrine", regex: "i)^(Infinite|\d{1,3})$"}
settings["BlenderIndex1"] := {enum: 59, type: "str", section: "Blender", regex: "i)^(Infinite|\d{1,3})$"}
settings["BlenderIndex2"] := {enum: 60, type: "str", section: "Blender", regex: "i)^(Infinite|\d{1,3})$"}
settings["BlenderIndex3"] := {enum: 61, type: "str", section: "Blender", regex: "i)^(Infinite|\d{1,3})$"}
settings["BlenderItem1"] := {enum: 62, type: "str", section: "Blender", regex: "i)^(blueextract|redextract|glue|Oil|enzymes|gumdrops|tropicaldrink|mooncharms|glitter|starjelly|purplepotion|softwax|hardwax|swirledwax|causticwax|fielddice|smoothdice|loadeddice|supersmoothie|Turpentine|None)$"}
settings["BlenderItem2"] := {enum: 63, type: "str", section: "Blender", regex: "i)^(blueextract|redextract|glue|oil|enzymes|gumdrops|tropicaldrink|mooncharms|glitter|starjelly|purplepotion|softwax|hardwax|swirledwax|causticwax|fielddice|smoothdice|loadeddice|supersmoothie|Turpentine|None)$"}
settings["BlenderItem3"] := {enum: 64, type: "str", section: "Blender", regex: "i)^(blueextract|redextract|glue|oil|enzymes|gumdrops|tropicaldrink|mooncharms|glitter|starjelly|purplepotion|softwax|hardwax|swirledwax|causticwax|fielddice|smoothdice|loadeddice|supersmoothie|Turpentine|None)$"}
settings["StickerStackItem"] := {enum: 65, type: "str", section: "Boost", regex: "i)^(tickets|sticker|sticker\+tickets)$"}
settings["StickerPrinterEgg"] := {enum: 66, type: "str", section: "Boost", regex: "i)^(Basic|Silver|Gold|Diamond|Mythic)$"}
settings["MondoLootDirection"] := {enum: 67, type: "str", section: "Collect", regex: "i)^(Left|Right|Random|Ignore)$"}
settings["PlanterName1"] := {enum: 68, type: "str", section: "Planters", regex: "i)^(PlasticPlanter|CandyPlanter|BlueClayPlanter|RedClayPlanter|TackyPlanter|PesticidePlanter|HeatTreatedPlanter|HydroponicPlanter|PetalPlanter|PlanterOfPlenty|PaperPlanter|TicketPlanter)$"}
settings["PlanterName2"] := {enum: 69, type: "str", section: "Planters", regex: "i)^(PlasticPlanter|CandyPlanter|BlueClayPlanter|RedClayPlanter|TackyPlanter|PesticidePlanter|HeatTreatedPlanter|HydroponicPlanter|PetalPlanter|PlanterOfPlenty|PaperPlanter|TicketPlanter)$"}
settings["PlanterName3"] := {enum: 70, type: "str", section: "Planters", regex: "i)^(PlasticPlanter|CandyPlanter|BlueClayPlanter|RedClayPlanter|TackyPlanter|PesticidePlanter|HeatTreatedPlanter|HydroponicPlanter|PetalPlanter|PlanterOfPlenty|PaperPlanter|TicketPlanter)$"}
settings["PlanterField1"] := {enum: 71, type: "str", section: "Planters", regex: "i)^(None|Bamboo|Blue Flower|Cactus|Clover|Coconut|Dandelion|Mountain Top|Mushroom|Pepper|Pine Tree|Pineapple|Pumpkin|Rose|Spider|Strawberry|Stump|Sunflower)$"}
settings["PlanterField2"] := {enum: 72, type: "str", section: "Planters", regex: "i)^(None|Bamboo|Blue Flower|Cactus|Clover|Coconut|Dandelion|Mountain Top|Mushroom|Pepper|Pine Tree|Pineapple|Pumpkin|Rose|Spider|Strawberry|Stump|Sunflower)$"}
settings["PlanterField3"] := {enum: 73, type: "str", section: "Planters", regex: "i)^(None|Bamboo|Blue Flower|Cactus|Clover|Coconut|Dandelion|Mountain Top|Mushroom|Pepper|Pine Tree|Pineapple|Pumpkin|Rose|Spider|Strawberry|Stump|Sunflower)$"}
settings["PlanterNectar1"] := {enum: 74, type: "str", section: "Planters", regex: "i)^(None|Comforting|Refreshing|Satisfying|Motivating|Invigorating)$"}
settings["PlanterNectar2"] := {enum: 75, type: "str", section: "Planters", regex: "i)^(None|Comforting|Refreshing|Satisfying|Motivating|Invigorating)$"}
settings["PlanterNectar3"] := {enum: 76, type: "str", section: "Planters", regex: "i)^(None|Comforting|Refreshing|Satisfying|Motivating|Invigorating)$"}
settings["PlanterHarvestFull1"] := {enum: 77, type: "str", section: "Planters", regex: "i)^(Full|Timed)$"}
settings["PlanterHarvestFull2"] := {enum: 78, type: "str", section: "Planters", regex: "i)^(Full|Timed)$"}
settings["PlanterHarvestFull3"] := {enum: 79, type: "str", section: "Planters", regex: "i)^(Full|Timed)$"}

;settings["discordMode"] := {enum: 1, type: "int", section: "Status", regex: "i)^(0|1|2)$"} dangerous
;settings["discordCheck"] := {enum: 2, type: "int", section: "Status", regex: "i)^(0|1)$"} dangerous
;settings["MainChannelCheck"] := {enum: 3, type: "int", section: "Status", regex: "i)^(0|1)$"} dangerous
settings["ReportChannelCheck"] := {enum: 4, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["WebhookEasterEgg"] := {enum: 5, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["ssCheck"] := {enum: 6, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["ssDebugging"] := {enum: 7, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["CriticalSSCheck"] := {enum: 8, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["AmuletSSCheck"] := {enum: 9, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["MachineSSCheck"] := {enum: 10, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["BalloonSSCheck"] := {enum: 11, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["ViciousSSCheck"] := {enum: 12, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["DeathSSCheck"] := {enum: 13, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["PlanterSSCheck"] := {enum: 14, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["HoneySSCheck"] := {enum: 15, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["criticalCheck"] := {enum: 16, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["CriticalErrorPingCheck"] := {enum: 17, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["DisconnectPingCheck"] := {enum: 18, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["GameFrozenPingCheck"] := {enum: 19, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["PhantomPingCheck"] := {enum: 20, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["UnexpectedDeathPingCheck"] := {enum: 21, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["EmergencyBalloonPingCheck"] := {enum: 22, type: "int", section: "Status", regex: "i)^(0|1)$"}
;settings["MacroState"] := {enum: 23, type: "int", regex: "i)^(0|1|2)$"} dangerous
settings["PlanterMode"] := {enum: 24, type: "int", section: "Planters", regex: "i)^(0|1|2)$"}
settings["MaxAllowedPlanters"] := {enum: 25, type: "int", section: "Planters", regex: "i)^(0|1|2|3)$"}
settings["HarvestInterval"] := {enum: 26, type: "int", section: "Planters", regex: "i)^\d{1,2}$"}
settings["AutomaticHarvestInterval"] := {enum: 27, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["HarvestFullGrown"] := {enum: 28, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["GotoPlanterField"] := {enum: 29, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["GatherFieldSipping"] := {enum: 30, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["ConvertFullBagHarvest"] := {enum: 31, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["GatherPlanterLoot"] := {enum: 32, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlasticPlanterCheck"] := {enum: 33, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["CandyPlanterCheck"] := {enum: 34, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["BlueClayPlanterCheck"] := {enum: 35, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["RedClayPlanterCheck"] := {enum: 36, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["TackyPlanterCheck"] := {enum: 37, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PesticidePlanterCheck"] := {enum: 38, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["HeatTreatedPlanterCheck"] := {enum: 39, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["HydroponicPlanterCheck"] := {enum: 40, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PetalPlanterCheck"] := {enum: 41, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PaperPlanterCheck"] := {enum: 42, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["TicketPlanterCheck"] := {enum: 43, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterOfPlentyCheck"] := {enum: 44, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["BambooFieldCheck"] := {enum: 45, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["BlueFlowerFieldCheck"] := {enum: 46, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["CactusFieldCheck"] := {enum: 47, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["CloverFieldCheck"] := {enum: 48, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["CoconutFieldCheck"] := {enum: 49, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["DandelionFieldCheck"] := {enum: 50, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MountainTopFieldCheck"] := {enum: 51, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MushroomFieldCheck"] := {enum: 52, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PepperFieldCheck"] := {enum: 53, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PineTreeFieldCheck"] := {enum: 54, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PineappleFieldCheck"] := {enum: 55, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PumpkinFieldCheck"] := {enum: 56, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["RoseFieldCheck"] := {enum: 57, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["SpiderFieldCheck"] := {enum: 58, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["StrawberryFieldCheck"] := {enum: 59, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["StumpFieldCheck"] := {enum: 60, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["SunflowerFieldCheck"] := {enum: 61, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MultiReset"] := {enum: 62, type: "int", section: "Settings", regex: "i)^(0|1|2|3)$"}
settings["ConvertMins"] := {enum: 63, type: "int", section: "Settings", regex: "i)^\d{1,2}$"}
settings["LastConvertBalloon"] := {enum: 64, type: "int", section: "Settings", regex: "i)^\d{1,10}$"}
settings["DisableToolUse"] := {enum: 65, type: "int", section: "Settings", regex: "i)^(0|1)$"}
settings["AnnounceGuidingStar"] := {enum: 66, type: "int", section: "Settings", regex: "i)^(0|1)$"}
settings["NewWalk"] := {enum: 67, type: "int", section: "Settings", regex: "i)^(0|1)$"}
settings["HiveSlot"] := {enum: 68, type: "int", section: "Settings", regex: "i)^[1-6]$"}
settings["HiveBees"] := {enum: 69, type: "int", section: "Settings", regex: "^([1-9]|[1-4][0-9]|50)$"}
settings["ConvertDelay"] := {enum: 70, type: "int", section: "Settings", regex: "i)^\d{1,2}$"}
settings["ReconnectMessage"] := {enum: 71, type: "int", section: "Settings", regex: "i)^(0|1)$"}
settings["PublicFallback"] := {enum: 72, type: "int", section: "Settings", regex: "i)^(0|1)$"}
settings["KeyDelay"] := {enum: 73, type: "int", section: "Settings", regex: "i)^\d{1,3}$"}
settings["FieldPatternReps1"] := {enum: 74, type: "int", section: "Gather", regex: "i)^[1-9]$"}
settings["FieldPatternReps2"] := {enum: 75, type: "int", section: "Gather", regex: "i)^[1-9]$"}
settings["FieldPatternReps3"] := {enum: 76, type: "int", section: "Gather", regex: "i)^[1-9]$"}
settings["FieldPatternShift1"] := {enum: 77, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternShift2"] := {enum: 78, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternShift3"] := {enum: 79, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternInvertFB1"] := {enum: 80, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternInvertFB2"] := {enum: 81, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternInvertFB3"] := {enum: 82, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternInvertLR1"] := {enum: 83, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternInvertLR2"] := {enum: 84, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldPatternInvertLR3"] := {enum: 85, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldUntilMins1"] := {enum: 86, type: "int", section: "Gather", regex: "i)^\d{1,4}$"}
settings["FieldUntilMins2"] := {enum: 87, type: "int", section: "Gather", regex: "i)^\d{1,4}$"}
settings["FieldUntilMins3"] := {enum: 88, type: "int", section: "Gather", regex: "i)^\d{1,4}$"}
settings["FieldUntilPack1"] := {enum: 89, type: "int", section: "Gather", regex: "i)^(5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$"}
settings["FieldUntilPack2"] := {enum: 90, type: "int", section: "Gather", regex: "i)^(5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$"}
settings["FieldUntilPack3"] := {enum: 91, type: "int", section: "Gather", regex: "i)^(5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$"}
settings["FieldSprinklerDist1"] := {enum: 92, type: "int", section: "Gather", regex: "i)^([1-9]|10)$"}
settings["FieldSprinklerDist2"] := {enum: 93, type: "int", section: "Gather", regex: "i)^([1-9]|10)$"}
settings["FieldSprinklerDist3"] := {enum: 94, type: "int", section: "Gather", regex: "i)^([1-9]|10)$"}
settings["FieldRotateTimes1"] := {enum: 95, type: "int", section: "Gather", regex: "i)^[1-4]$"}
settings["FieldRotateTimes2"] := {enum: 96, type: "int", section: "Gather", regex: "i)^[1-4]$"}
settings["FieldRotateTimes3"] := {enum: 97, type: "int", section: "Gather", regex: "i)^[1-4]$"}
settings["FieldDriftCheck1"] := {enum: 98, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldDriftCheck2"] := {enum: 99, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["FieldDriftCheck3"] := {enum: 100, type: "int", section: "Gather", regex: "i)^(0|1)$"}
settings["ClockCheck"] := {enum: 101, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastClock"] := {enum: 102, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["MondoBuffCheck"] := {enum: 103, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastMondoBuff"] := {enum: 104, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["AntPassCheck"] := {enum: 105, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastAntPass"] := {enum: 106, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["RoboPassCheck"] := {enum: 107, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastRoboPass"] := {enum: 108, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["HoneyDisCheck"] := {enum: 109, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastHoneyDis"] := {enum: 110, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["TreatDisCheck"] := {enum: 111, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastTreatDis"] := {enum: 112, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BlueberryDisCheck"] := {enum: 113, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBlueberryDis"] := {enum: 114, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["StrawberryDisCheck"] := {enum: 115, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastStrawberryDis"] := {enum: 116, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["CoconutDisCheck"] := {enum: 117, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastCoconutDis"] := {enum: 118, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["RoyalJellyDisCheck"] := {enum: 119, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastRoyalJellyDis"] := {enum: 120, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["GlueDisCheck"] := {enum: 121, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastGlueDis"] := {enum: 122, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BlueBoostCheck"] := {enum: 123, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBlueBoost"] := {enum: 124, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["RedBoostCheck"] := {enum: 125, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastRedBoost"] := {enum: 126, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["MountainBoostCheck"] := {enum: 127, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastMountainBoost"] := {enum: 128, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BeesmasGatherInterruptCheck"] := {enum: 129, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StockingsCheck"] := {enum: 130, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastStockings"] := {enum: 131, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["WreathCheck"] := {enum: 132, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastWreath"] := {enum: 133, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["FeastCheck"] := {enum: 134, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastFeast"] := {enum: 135, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["GingerbreadCheck"] := {enum: 136, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastGingerbread"] := {enum: 137, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["SnowMachineCheck"] := {enum: 138, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastSnowMachine"] := {enum: 139, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["CandlesCheck"] := {enum: 140, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastCandles"] := {enum: 141, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["SamovarCheck"] := {enum: 142, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastSamovar"] := {enum: 143, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["LidArtCheck"] := {enum: 144, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastLidArt"] := {enum: 145, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["GummyBeaconCheck"] := {enum: 146, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastGummyBeacon"] := {enum: 147, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["MonsterRespawnTime"] := {enum: 148, type: "int", section: "Collect", regex: "i)^(40|[1-3]?[0-9])$"}
settings["BugrunInterruptCheck"] := {enum: 149, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunLadybugsCheck"] := {enum: 150, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunLadybugsLoot"] := {enum: 151, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBugrunLadybugs"] := {enum: 152, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BugrunRhinoBeetlesCheck"] := {enum: 153, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunRhinoBeetlesLoot"] := {enum: 154, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBugrunRhinoBeetles"] := {enum: 155, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BugrunSpiderCheck"] := {enum: 156, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunSpiderLoot"] := {enum: 157, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBugrunSpider"] := {enum: 158, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BugrunMantisCheck"] := {enum: 159, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunMantisLoot"] := {enum: 160, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBugrunMantis"] := {enum: 161, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BugrunScorpionsCheck"] := {enum: 162, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunScorpionsLoot"] := {enum: 163, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBugrunScorpions"] := {enum: 164, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["BugrunWerewolfCheck"] := {enum: 165, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BugrunWerewolfLoot"] := {enum: 166, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastBugrunWerewolf"] := {enum: 167, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["TunnelBearCheck"] := {enum: 168, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["TunnelBearBabyCheck"] := {enum: 169, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastTunnelBear"] := {enum: 170, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["KingBeetleCheck"] := {enum: 171, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["KingBeetleBabyCheck"] := {enum: 172, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastKingBeetle"] := {enum: 173, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["StumpSnailCheck"] := {enum: 174, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastStumpSnail"] := {enum: 175, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["CommandoCheck"] := {enum: 176, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastCommando"] := {enum: 177, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["CocoCrabCheck"] := {enum: 178, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastCocoCrab"] := {enum: 179, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["StingerCheck"] := {enum: 180, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StingerPepperCheck"] := {enum: 181, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StingerMountainTopCheck"] := {enum: 182, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StingerRoseCheck"] := {enum: 183, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StingerCactusCheck"] := {enum: 184, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StingerSpiderCheck"] := {enum: 185, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StingerCloverCheck"] := {enum: 186, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["BoostChaserCheck"] := {enum: 187, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["FieldBoosterMins"] := {enum: 188, type: "int", section: "Boost", regex: "i)^(0|5|10|15|20|30)$"}
settings["HotbarTime2"] := {enum: 189, type: "int", section: "Boost", regex: "i)^\d{1,5}$"}
settings["HotbarTime3"] := {enum: 190, type: "int", section: "Boost", regex: "i)^\d{1,5}$"}
settings["HotbarTime4"] := {enum: 191, type: "int", section: "Boost", regex: "i)^\d{1,5}$"}
settings["HotbarTime5"] := {enum: 192, type: "int", section: "Boost", regex: "i)^\d{1,5}$"}
settings["HotbarTime6"] := {enum: 193, type: "int", section: "Boost", regex: "i)^\d{1,5}$"}
settings["HotbarTime7"] := {enum: 194, type: "int", section: "Boost", regex: "i)^\d{1,5}$"}
settings["LastHotkey2"] := {enum: 195, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastHotkey3"] := {enum: 196, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastHotkey4"] := {enum: 197, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastHotkey5"] := {enum: 198, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastHotkey6"] := {enum: 199, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastHotkey7"] := {enum: 200, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastHotkey7"] := {enum: 201, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastWhirligig"] := {enum: 202, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastEnzymes"] := {enum: 203, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastGlitter"] := {enum: 204, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["LastSnowflake"] := {enum: 205, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
;settings["LastWindShrine"] := {enum: 206, type: "int", section: "Boost", regex: "i)^\d{1,10}$"} obsolete
settings["LastMicroConverter"] := {enum: 207, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["QuestGatherMins"] := {enum: 208, type: "int", section: "Quests", regex: "i)^(100|[1-9][0-9]?)$"}
settings["PolarQuestCheck"] := {enum: 209, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["PolarQuestGatherInterruptCheck"] := {enum: 210, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["HoneyQuestCheck"] := {enum: 211, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["BlackQuestCheck"] := {enum: 212, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["LastBlackQuest"] := {enum: 213, type: "int", section: "Quests", regex: "i)^\d{1,10}$"}
settings["BuckoQuestCheck"] := {enum: 214, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["BuckoQuestGatherInterruptCheck"] := {enum: 215, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["RileyQuestCheck"] := {enum: 216, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["RileyQuestGatherInterruptCheck"] := {enum: 217, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["KingBeetleAmuletMode"] := {enum: 218, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["ShellAmuletMode"] := {enum: 219, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["NightAnnouncementCheck"] := {enum: 220, type: "int", section: "Status", regex: "i)^(0|1)$"}
;settings["PublicJoined"] := {enum: 221, type: "int", regex: "i)^(0|1)$"} dangerous
settings["DebugLogEnabled"] := {enum: 222, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["StingerDailyBonusCheck"] := {enum: 223, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["GatherDoubleReset"] := {enum: 224, type: "int", section: "Settings", regex: "i)^(0|1)$"}
settings["HoneystormCheck"] := {enum: 225, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastHoneystorm"] := {enum: 226, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["RBPDelevelCheck"] := {enum: 227, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastRBPDeLevel"] := {enum: 228, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["ShrineCheck"] := {enum: 229, type: "int", section: "Shrine", regex: "i)^(0|1)$"}
settings["BlenderCheck"] := {enum: 230, type: "int", section: "Blender", regex: "i)^(0|1)$"}
settings["ShrineAmount1"] := {enum: 231, type: "int", section: "Shrine", regex: "i)^\d{1,3}$"}
settings["ShrineAmount2"] := {enum: 232, type: "int", section: "Shrine", regex: "i)^\d{1,3}$"}
settings["BlenderAmount1"] := {enum: 233, type: "int", section: "Blender", regex: "i)^\d{1,3}$"}
settings["BlenderAmount2"] := {enum: 234, type: "int", section: "Blender", regex: "i)^\d{1,3}$"}
settings["BlenderAmount3"] := {enum: 235, type: "int", section: "Blender", regex: "i)^\d{1,3}$"}
settings["BlenderRot"] := {enum: 236, type: "int", section: "Blender", regex: "i)^\d{1,3}$"}
settings["TimerInterval"] := {enum: 237, type: "int", section: "Blender", regex: "i)^\d{1,8}$"}
settings["LastBlenderRot"] := {enum: 238, type: "int", section: "Blender", regex: "i)^(1|2|3)$"}
settings["BlenderTime1"] := {enum: 239, type: "int", section: "Blender", regex: "i)^\d{1,10}$"}
settings["BlenderTime2"] := {enum: 240, type: "int", section: "Blender", regex: "i)^\d{1,10}$"}
settings["BlenderTime3"] := {enum: 241, type: "int", section: "Blender", regex: "i)^\d{1,10}$"}
settings["MondoSecs"] := {enum: 242, type: "int", section: "Collect", regex: "i)^\d{1,3}$"}
settings["MPlanterGatherA"] := {enum: 243, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGather1"] := {enum: 244, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGather2"] := {enum: 245, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGather3"] := {enum: 246, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffModeA"] := {enum: 247, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffMode1"] := {enum: 248, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffMode2"] := {enum: 249, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffMode3"] := {enum: 250, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["BlueFlowerBoosterCheck"] := {enum: 251, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["BambooBoosterCheck"] := {enum: 252, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["PineTreeBoosterCheck"] := {enum: 253, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["DandelionBoosterCheck"] := {enum: 254, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["SunflowerBoosterCheck"] := {enum: 255, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["CloverBoosterCheck"] := {enum: 256, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["SpiderBoosterCheck"] := {enum: 257, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["PineappleBoosterCheck"] := {enum: 258, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["CactusBoosterCheck"] := {enum: 259, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["PumpkinBoosterCheck"] := {enum: 260, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["MushroomBoosterCheck"] := {enum: 261, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["StrawberryBoosterCheck"] := {enum: 262, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["RoseBoosterCheck"] := {enum: 263, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["MPlanterHold1"] := {enum: 264, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterHold2"] := {enum: 265, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterHold3"] := {enum: 266, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["BrownQuestCheck"] := {enum: 267, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["LastBrownQuest"] := {enum: 268, type: "int", section: "Quests", regex: "i)^\d{1,10}$"}
settings["StickerStackCheck"] := {enum: 269, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["LastStickerStack"] := {enum: 270, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["StickerStackMode"] := {enum: 271, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["StickerStackTimer"] := {enum: 272, type: "int", section: "Boost", regex: "i)^(?!0)(?:9\d\d|\d{4}|[1-7]\d{4}|8[0-5]\d{3}|86[0-3]\d{2}|86400)$"}
settings["StickerPrinterCheck"] := {enum: 273, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["LastStickerPrinter"] := {enum: 274, type: "int", section: "Boost", regex: "i)^\d{1,10}$"}
settings["AntPassBuyCheck"] := {enum: 275, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["StickerStackHive"] := {enum: 276, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["StickerStackCub"] := {enum: 277, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["QuestBoostCheck"] := {enum: 278, type: "int", section: "Quests", regex: "i)^(0|1)$"}
settings["MConvertFullBagHarvest"] := {enum: 279, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGatherA"] := {enum: 280, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGather1"] := {enum: 281, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGather2"] := {enum: 282, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterGather3"] := {enum: 283, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterSmoking1"] := {enum: 284, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterSmoking2"] := {enum: 285, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPlanterSmoking3"] := {enum: 286, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffModeA"] := {enum: 287, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffMode1"] := {enum: 288, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffMode2"] := {enum: 289, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["MPuffMode3"] := {enum: 290, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterHarvestNow1"] := {enum: 291, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterHarvestNow2"] := {enum: 292, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterHarvestNow3"] := {enum: 293, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterSS1"] := {enum: 294, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterSS2"] := {enum: 295, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterSS3"] := {enum: 296, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterHarvestTime1"] := {enum: 297, type: "int", section: "Planters", regex: "i)^\d{1,10}$"}
settings["PlanterHarvestTime2"] := {enum: 298, type: "int", section: "Planters", regex: "i)^\d{1,10}$"}
settings["PlanterHarvestTime3"] := {enum: 299, type: "int", section: "Planters", regex: "i)^\d{1,10}$"}
settings["PlanterEstPercent1"] := {enum: 300, type: "int", section: "Planters", regex: "i)^\d{1,3}$"}
settings["PlanterEstPercent2"] := {enum: 301, type: "int", section: "Planters", regex: "i)^\d{1,3}$"}
settings["PlanterEstPercent3"] := {enum: 302, type: "int", section: "Planters", regex: "i)^\d{1,3}$"}
settings["PlanterGlitter1"] := {enum: 303, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterGlitter2"] := {enum: 304, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterGlitter3"] := {enum: 305, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterGlitterC1"] := {enum: 306, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterGlitterC2"] := {enum: 307, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterGlitterC3"] := {enum: 308, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PlanterManualCycle1"] := {enum: 309, type: "int", section: "Planters", regex: "i)^\d$"}
settings["PlanterManualCycle2"] := {enum: 310, type: "int", section: "Planters", regex: "i)^\d$"}
settings["PlanterManualCycle3"] := {enum: 311, type: "int", section: "Planters", regex: "i)^\d$"}
settings["NormalMemoryMatchCheck"] := {enum: 312, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastNormalMemoryMatch"] := {enum: 313, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["MegaMemoryMatchCheck"] := {enum: 314, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastMegaMemoryMatch"] := {enum: 315, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["ExtremeMemoryMatchCheck"] := {enum: 316, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastExtremeMemoryMatch"] := {enum: 317, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["NightMemoryMatchCheck"] := {enum: 318, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastNightMemoryMatch"] := {enum: 319, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["WinterMemoryMatchCheck"] := {enum: 320, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["LastWinterMemoryMatch"] := {enum: 321, type: "int", section: "Collect", regex: "i)^\d{1,10}$"}
settings["MemoryMatchInterruptCheck"] := {enum: 322, type: "int", section: "Collect", regex: "i)^(0|1)$"}
settings["MicroConverterMatchIgnore"] := {enum: 323, type: "int", section: "Collect"}
settings["SunflowerSeedMatchIgnore"] := {enum: 324, type: "int", section: "Collect"}
settings["JellyBeanMatchIgnore"] := {enum: 325, type: "int", section: "Collect"}
settings["RoyalJellyMatchIgnore"] := {enum: 326, type: "int", section: "Collect"}
settings["TicketMatchIgnore"] := {enum: 327, type: "int", section: "Collect"}
settings["CyanTrimMatchIgnore"] := {enum: 328, type: "int", section: "Collect"}
settings["OilMatchIgnore"] := {enum: 329, type: "int", section: "Collect"}
settings["StrawberryMatchIgnore"] := {enum: 330, type: "int", section: "Collect"}
settings["CoconutMatchIgnore"] := {enum: 331, type: "int", section: "Collect"}
settings["TropicalDrinkMatchIgnore"] := {enum: 332, type: "int", section: "Collect"}
settings["RedExtractMatchIgnore"] := {enum: 333, type: "int", section: "Collect"}
settings["MagicBeanMatchIgnore"] := {enum: 334, type: "int", section: "Collect"}
settings["PineappleMatchIgnore"] := {enum: 335, type: "int", section: "Collect"}
settings["StarJellyMatchIgnore"] := {enum: 336, type: "int", section: "Collect"}
settings["EnzymeMatchMatchIgnore"] := {enum: 337, type: "int", section: "Collect"}
settings["BlueExtractMatchIgnore"] := {enum: 338, type: "int", section: "Collect"}
settings["GumdropMatchIgnore"] := {enum: 339, type: "int", section: "Collect"}
settings["FieldDiceMatchIgnore"] := {enum: 340, type: "int", section: "Collect"}
settings["MoonCharmMatchIgnore"] := {enum: 341, type: "int", section: "Collect"}
settings["BlueberryMatchIgnore"] := {enum: 342, type: "int", section: "Collect"}
settings["GlitterMatchIgnore"] := {enum: 343, type: "int", section: "Collect"}
settings["StingerMatchIgnore"] := {enum: 344, type: "int", section: "Collect"}
settings["TreatMatchIgnore"] := {enum: 345, type: "int", section: "Collect"}
settings["GlueMatchIgnore"] := {enum: 346, type: "int", section: "Collect"}
settings["CloudVialMatchIgnore"] := {enum: 347, type: "int", section: "Collect"}
settings["SoftWaxMatchIgnore"] := {enum: 348, type: "int", section: "Collect"}
settings["HardWaxMatchIgnore"] := {enum: 349, type: "int", section: "Collect"}
settings["SwirledWaxMatchIgnore"] := {enum: 350, type: "int", section: "Collect"}
settings["NightBellMatchIgnore"] := {enum: 351, type: "int", section: "Collect"}
settings["HoneysuckleMatchIgnore"] := {enum: 352, type: "int", section: "Collect"}
settings["SuperSmoothieMatchIgnore"] := {enum: 353, type: "int", section: "Collect"}
settings["SmoothDiceMatchIgnore"] := {enum: 354, type: "int", section: "Collect"}
settings["NeonberryMatchIgnore"] := {enum: 355, type: "int", section: "Collect"}
settings["GingerbreadMatchIgnore"] := {enum: 356, type: "int", section: "Collect"}
settings["SilverEggMatchIgnore"] := {enum: 357, type: "int", section: "Collect"}
settings["GoldEggMatchIgnore"] := {enum: 358, type: "int", section: "Collect"}
settings["DiamondEggMatchIgnore"] := {enum: 359, type: "int", section: "Collect"}
settings["CoconutBoosterCheck"] := {enum: 360, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["StumpBoosterCheck"] := {enum: 361, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["PepperBoosterCheck"] := {enum: 362, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["HoneyUpdateSSCheck"] := {enum: 363, type: "int", section: "Status", regex: "i)^(0|1)$"}
settings["StickerStackVoucher"] := {enum: 364, type: "int", section: "Boost", regex: "i)^(0|1)$"}
settings["MGatherPlanterLoot"] := {enum: 365, type: "int", section: "Planters", regex: "i)^(0|1)$"}
settings["PriorityListNumeric"] := {enum: 366, type: "int", section: "Settings", regex: "i)^[1-8]{8}$"}